---
- hosts: 172.31.19.128
  become: yes
  tasks: 
  - name: i want to excute direct linux commands
    command: hostname -f
    register: myresult

  - name: i want to display frist task result
    debug: 
     msg: "{{myresult}}"


  - name: i want to install git
    apt:
      name: git
      state: present
    when: myresult.stderr ==""

  - name: i want to install tree
    apt:
      name: tree
      state: present
    when: myresult.stderr !==""   