---
- hosts: 172.31.19.128 
  become: yes
  tasks:
  - include_tasks: myfiles.yml
  - name: i want to install webserver
    apt:
      name: apache2
      state: present
    notify: restart webserver


  - name: i want to copy static files into ansible nodes side
    copy:
      src: mystaticfile.html
      dest: /var/www/html/index.html
    notify: restart webserver

  - name: i want to copy dynamic files into ansible nodes side
    template:
      src: myindex.j2
      dest: /var/www/html/index.html 
    notify: restart webserver
  - name: i want to download files from remote      
    get_url:
      url: https://get.jenkins.io/war-stable/2.332.3/jenkins.war
      dest: /home/ubuntu/jenkins.war
      force_basic_auth: yes


  - name: i want to create folder
    file:
      path: /home/ubuntu/myfolder
      state: directory
  handlers:
  - name: restart webserver
    service:
       name: apache2
       state: restarted