---
- hosts: 172.31.19.128 
  become: yes
  tasks:
  - include_tasks: myfiles.yml
  - name: i want to install webserver
    apt:
      name: apache2
      state: present


  - name: i want to copy static files into ansible nodes side
    template:
      src: mystaticfile.html
      dest: /var/www/html/index.html

  - name: i want to copy dynamic files into ansible nodes side
    template:
      src: myindex.j2
      dest: /var/www/html/index.html 

      
  - name: i want to download files from remote into nodes
    get-url:
    url: https://get.jenkins.io/war-stable/2.332.3/jenkins.war
    dest: /home/ubuntu/jenkins.war
    force_basic_auth: yes
    