---
- hosts: all
  become: yes
  tasks: 
  - name: install webserver
    apt: 
      name: apache2
      state: present
    when: ansible_os_family=="Debian"

  - name: start webserver
    service:
       name: apache2
       state: restarted
    when: ansible_os_family=="Debian"

  - name: install webserver on redhat
    yum:
      name: httpd
      state: present
    when: ansible_os_family=="RedHat"

  - name: start webserver on redhat
    service:
      name: httpd
      state: restarted
    when: ansible_os_family=="Redhat"
    
      