---
- hosts: all
  become: yes
  tasks: 
  - name: install webserver on ubuntu
    apt: 
      name: "{{mywebpackonubuntu}}"
      state: present
    when: ansible_os_family=="Debian"

  - name: start webserver on ubuntu
    service:
       name: "{{mywebpackonubuntu}}"
       state: restarted
    when: ansible_os_family=="Debian"

  - name: install webserver on redhat
    yum:
      name: "{{mywebpackonredhat}}"
      state: present
    when: ansible_os_family=="RedHat"


  - name: start webserver on redhat
    service:
      name: "{{mywebpackonredhat}}"
      state: started
    when: ansible_os_family=="RedHat"
  
    
      