---
# tasks file for mytomneha
- include_tasks: myadduser.yml
- include_tasks: installjava.yml
- include_tasks: installtomcat.yml
- include_tasks: permissions.yml
- include_tasks: tomcatadminuser.yml
- include_tasks: tomcatservice.yml
- include_tasks: tomcatstart.yml
